"""add scheduled posts

Revision ID: f554747e3fb1
Revises: c81d42f5f790
Create Date: 2026-09-02 16:13:32.509711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f554747e3fb1'
down_revision: Union[str, Sequence[str], None] = 'c81d42f5f790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('hint_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hint_id'], ['hints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_posts_course_id'), 'scheduled_posts', ['course_id'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_hint_id'), 'scheduled_posts', ['hint_id'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_project_id'), 'scheduled_posts', ['project_id'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_scheduled_at'), 'scheduled_posts', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_status'), 'scheduled_posts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_posts_status'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_scheduled_at'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_project_id'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_hint_id'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_course_id'), table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    # ### end Alembic commands ###
